name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGQ5OGM2MGEtM2Q1NC00YjhjLTk5NGQtZjhmNTUyMTIyNzEyIiwidGVuYW50X2lkIjoiOGFkNmZkMGM1ODU3NGZkYjFjMzkxZDQwMmQ3ZGRjZjJjYjE0NTZhMzYzYjA3OTE3ZDYzYTJlMWRlZDI2MzBhZiIsImludGVybmFsX3NlY3JldCI6IjJkY2I0NmI5LWJkZDUtNDliNS04OWIyLTY5ODE3ZDdlN2Q4ZCJ9.qpyMhKINkz1NDuytw_SMxrFDyqJ8rR0yS2jsUyQiRK4"
JWT_SECRET = "password@7346"
